org: arcdigital
app: cl-practical
service: logger
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10

functions:
  logger:
    handler: handler.log
    events:
      - s3: 
          bucket: ${output:worker.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: events/
            - suffix: .json
          existing: true