name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements_dev.txt
          pip install pytest pytest-cov

      - name: Test API Function
        run: |
          cd api && pytest test_handler.py
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: none
          AWS_SECRET_ACCESS_KEY: none

      - name: Test Worker Function
        run: |
          cd worker && pytest test_handler.py
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: none
          AWS_SECRET_ACCESS_KEY: none

      - name: Test Logger Function
        run: |
          cd logger && pytest test_handler.py
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: none
          AWS_SECRET_ACCESS_KEY: none
  
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
